### PR TITLE
Juice-67: make_grid_velocities_incompressible()

### PR DESCRIPTION
**Pull request by kadealicious**
- Implemented make_grid_velocities_incompressible()
- Implemented get_grid_cell_type()
       - Returns 0 for solids or out-of-bounds coordinates and 1 for fluid or air.
       - Used in calculating divergence, adjusted for collisions with solids.

### CODE REVIEW

**Review by r3dc0g — COMMENTED** [review]
Why is x component negative in the returning value within get_cell_coordinates_from_position() ?

**Comment by kadealicious** [comment]
> Why is x component negative in the returning value within get_cell_coordinates_from_position() ?

This is because the grid is organized as [rows, columns], with rows extending downward.  Because of this, we know that any y-position on the grid will be negative (the grid is formed from 0,0 in the top left.  We chose to make the grid extend downward, meaning all valid particle y-coordinates will be negative.).  Therefore, to get the correct row index, we must invert the y-coordinate passed into the function to produce a valid grid row index value.

I tested this function by setting various velocities around the grid and querying the velocity by converting a particlel position to a grid cell position.  Note that the function will only return valid cells if your original particle position is valid, otherwise you will get a  "hypothetical" grid cell position.

This is the issue with organizing the grid why rows and columns instead of by x and y: extra math is required and it is less intuitive.  Unfortunately I think it'd be a bad idea to go back and change it now, instead we should just make getter and setter functions that abstract grid cell access.

**Comment by r3dc0g** [comment]
I see. I think I miscommunicated with what I told you about the grid. I think I meant to say that the index (0, 0) of the grid points will be in the upper-left. For the sake of simplicity, I think we should keep (x,y) (0, 0) in the bottom-left. This was what I had in mind when making my get_velocity_point_pos() function. Does this compicate things too much?

**Comment by r3dc0g** [comment]
Unless we add more data and create a structure for a grid cell, we will need to continue to use row and column to index the different points within in the grid and x, y for points within the particle world and connect the two. Do you think the addition of a grid cell structure that stores pointers to the velocity points and x, y position data for easy access would work?

**Review by r3dc0g — APPROVED** [review]
Cool stuff Kade, thanks!

**Pull request merged**
